// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvABOnJ5HE4Xv0NTsHJgxDb4QKBc4DhBw',
    appId: '1:526416639405:web:0be2d2c3acc23621bf9d24',
    messagingSenderId: '526416639405',
    projectId: 'akhbar-alyoum-academy',
    authDomain: 'akhbar-alyoum-academy.firebaseapp.com',
    storageBucket: 'akhbar-alyoum-academy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9F3YeLcYgOiOwyZ3Vc9Ccg4JLF4xxPY8',
    appId: '1:526416639405:android:36e4e77aa1cb6607bf9d24',
    messagingSenderId: '526416639405',
    projectId: 'akhbar-alyoum-academy',
    storageBucket: 'akhbar-alyoum-academy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3VM-HnAqBmIF0DZXtXCSkCzkBIFsy730',
    appId: '1:526416639405:ios:f53aeff282413422bf9d24',
    messagingSenderId: '526416639405',
    projectId: 'akhbar-alyoum-academy',
    storageBucket: 'akhbar-alyoum-academy.appspot.com',
    iosBundleId: 'com.example.akbarAlYoumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3VM-HnAqBmIF0DZXtXCSkCzkBIFsy730',
    appId: '1:526416639405:ios:f53aeff282413422bf9d24',
    messagingSenderId: '526416639405',
    projectId: 'akhbar-alyoum-academy',
    storageBucket: 'akhbar-alyoum-academy.appspot.com',
    iosBundleId: 'com.example.akbarAlYoumApp',
  );
}
